services:
  currency:
    restart: unless-stopped
    build: ./currency
    ports:
      - 8083
    environment:
      - PORT=8083
      - NETWORK=tcp
      - COINGEKCO_URL=https://api.coingecko.com/api/v3/simple/price?ids=%s&vs_currencies=%s
      - COINAPI_URL=https://rest.coinapi.io/v1/exchangerate/%v/%v
      - COIN_API_KEY=FE1CB696-E794-4291-BECE-339379BA0726
      - KUNA_URL=https://api.kuna.io/v4/markets/public/tickers?pairs=%s_%s

  storage:
    restart: unless-stopped
    build: ./storage
    ports:
      - 8082
    environment:
      - STORAGE_PATH=./emails/source/emails.csv
      - PORT=8082
      - NETWORK=tcp

  email:
    restart: unless-stopped
    build: ./email
    ports:
      - 8081
    environment:
      - EMAIL_HOST=smtp.gmail.com
      - EMAIL_PORT=587
      - EMAIL_SENDER=genesistesttask7@gmail.com
      - EMAIL_PASS=jwajyxamarmpbdbi
      - NETWORK=tcp
      - PORT=8081

  api:
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./api/Dockerfile
    ports:
      - 8080:8080
    environment:
      - EMAIL_SERVICE_PORT=8081
      - STORAGE_SERVICE_PORT=8082
      - CURRENCY_SERVICE_PORT=8083
      - EMAIL_NETWORK=email
      - CURRENCY_NETWORK=currency
      - STORAGE_NETWORK=storage
      - PORT=8080